/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo1.app;

class MessageUtils {
    public static String getMessage() {
        return "hello      world!  goodbye    cruel world! hello         again!";
    }
}
